### ISSUE TITLE
Problems with the simulation process and results

### ISSUE THREAD

**Issue by Azircarry** [sriram-2502/KoopmanMPC_Quadrotor#1]
Hello, after I ran the main.m file, I got the following result
![image](https://github.com/sriram-2502/KoopmanMPC_Quadrotor/assets/114214508/0c95cc2e-c73d-4571-8667-f1fe7fc5498e)
![image](https://github.com/sriram-2502/KoopmanMPC_Quadrotor/assets/114214508/a3fe65f5-2bde-44e1-b9a1-94b067083143)

I want to know how to get other result graphs in the paper, in addition, from the results I run, the algorithm is not very good, can you help me, thank you very much！
Maybe my question is stupid, but I sincerely hope you can help me, so sorry to bother you

**Comment by sriram-2502** [comment]
Please switch to the MECC branch and run the code to reproduce the results of the paper. The main branch is still under development towards an extension of this work.
